# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vision.ui'
#
# Created: Sun Oct 27 22:03:54 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Vision(object):
    def setupUi(self, Vision):
        Vision.setObjectName(_fromUtf8("Vision"))
        Vision.resize(796, 613)
        self.centralwidget = QtGui.QWidget(Vision)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 331, 211))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.frontcam_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.frontcam_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frontcam_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frontcam_2.setObjectName(_fromUtf8("frontcam_2"))
        self.vboxlayout.addWidget(self.frontcam_2)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(410, 50, 341, 211))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self._2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.frontcamfiltered = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.frontcamfiltered.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frontcamfiltered.setFrameShadow(QtGui.QFrame.Raised)
        self.frontcamfiltered.setObjectName(_fromUtf8("frontcamfiltered"))
        self._2.addWidget(self.frontcamfiltered)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 330, 331, 201))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self._4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self._4.setMargin(0)
        self._4.setObjectName(_fromUtf8("_4"))
        self.bottomcam_2 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.bottomcam_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottomcam_2.setFrameShadow(QtGui.QFrame.Raised)
        self.bottomcam_2.setObjectName(_fromUtf8("bottomcam_2"))
        self._4.addWidget(self.bottomcam_2)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(410, 330, 341, 201))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self._3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self._3.setMargin(0)
        self._3.setObjectName(_fromUtf8("_3"))
        self.bottomcamfiltered = QtGui.QFrame(self.verticalLayoutWidget_4)
        self.bottomcamfiltered.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottomcamfiltered.setFrameShadow(QtGui.QFrame.Raised)
        self.bottomcamfiltered.setObjectName(_fromUtf8("bottomcamfiltered"))
        self._3.addWidget(self.bottomcamfiltered)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 260, 811, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.frontfilter = QtGui.QComboBox(self.centralwidget)
        self.frontfilter.setGeometry(QtCore.QRect(190, 10, 291, 27))
        self.frontfilter.setObjectName(_fromUtf8("frontfilter"))
        self.frontfilter.addItem(_fromUtf8(""))
        self.frontfilter.addItem(_fromUtf8(""))
        self.frontfilter.addItem(_fromUtf8(""))
        self.bottomfilter = QtGui.QComboBox(self.centralwidget)
        self.bottomfilter.setGeometry(QtCore.QRect(200, 290, 291, 27))
        self.bottomfilter.setObjectName(_fromUtf8("bottomfilter"))
        self.bottomfilter.addItem(_fromUtf8(""))
        self.bottomfilter.addItem(_fromUtf8(""))
        self.bottomfilter.addItem(_fromUtf8(""))
        self.bottomcam = QtGui.QLabel(self.centralwidget)
        self.bottomcam.setGeometry(QtCore.QRect(20, 290, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bottomcam.setFont(font)
        self.bottomcam.setObjectName(_fromUtf8("bottomcam"))
        self.frontcam = QtGui.QLabel(self.centralwidget)
        self.frontcam.setGeometry(QtCore.QRect(20, 20, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frontcam.setFont(font)
        self.frontcam.setObjectName(_fromUtf8("frontcam"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(370, 40, 20, 221))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(370, 320, 20, 251))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        Vision.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Vision)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        Vision.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Vision)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Vision.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(Vision)
        self.actionOpen.setShortcut(_fromUtf8(""))
        self.actionOpen.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(Vision)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(Vision)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Vision)
        QtCore.QMetaObject.connectSlotsByName(Vision)

    def retranslateUi(self, Vision):
        Vision.setWindowTitle(QtGui.QApplication.translate("Vision", "Vision", None, QtGui.QApplication.UnicodeUTF8))
        self.frontfilter.setItemText(0, QtGui.QApplication.translate("Vision", "Filter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.frontfilter.setItemText(1, QtGui.QApplication.translate("Vision", "Filter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.frontfilter.setItemText(2, QtGui.QApplication.translate("Vision", "Filter 3", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomfilter.setItemText(0, QtGui.QApplication.translate("Vision", "Filter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomfilter.setItemText(1, QtGui.QApplication.translate("Vision", "Filter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomfilter.setItemText(2, QtGui.QApplication.translate("Vision", "Filter 3", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomcam.setText(QtGui.QApplication.translate("Vision", "Bottom Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.frontcam.setText(QtGui.QApplication.translate("Vision", "Front Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Vision", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Vision", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Vision", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Vision", "&Quit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Vision = QtGui.QMainWindow()
    ui = Ui_Vision()
    ui.setupUi(Vision)
    Vision.show()
    sys.exit(app.exec_())

