#node search request
bool search_request
#node task complete request
bool task_complete_request
controller task_complete_ctrl
---
#node search response
bool search_response
#node task response
bool task_complete_response
