controller_frequency: 5.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:

#Robot Config Params

  acc_lim_x: 0.1428
  acc_lim_y: 0.1
  acc_lim_theta: 0.5

  max_vel_x: 0.5
  min_vel_x: 0.3
  max_vel_theta: 5
  min_vel_theta: -5
  min_in_place_rotational_vel: 2
  
  escape_vel: -0.001

  holonomic_robot: false

#Goal Tolerance Params

  yaw_goal_tolerance: 1 #tolerance in radians
  xy_goal_tolerance: 1 # 5 cm ; will literally stop within a 1m dia circle centered at the goal point
  latch_xy_goal_tolerance: true

#Forward simulation Params
  sim_time: 2
  sim_granularity: 0.75
  angular_sim_granularity: 0.025
  vx_samples: 15
  vtheta_samples: 15

#Trajectory Scoring Params

  meter_scoring: true
  pdist_scale: 1
  gdist_scale: 0.95
  occdist_scale: 0.05
  heading_lookahead: 4
  heading_scoring: true
  heading_scoring_timestep: 0.1
  dwa: false
  publish_cost_grid_pc: true
  global_frame_id: odom

#Oscillation Prevention Params
  oscillation_reset_dist: 0.01

#Global Plan Params
  prune_plan: true

#Other params
  simple_attractor: false

