controller_frequency: 10.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:

#Robot Config Params

  acc_lim_x: 0.1
  acc_lim_y: 0.1
  acc_lim_theta: 0.5

  max_vel_x: 0.3
  min_vel_x: 0
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_rotational_vel: 0.1
  
  escape_vel: -0.001

  holonomic_robot: false
  y_vels: [-0.3 -0.2 -0.1 0.1 0.2 0.3]

#Goal Tolerance Params

  yaw_goal_tolerance: 0.2 #tolerance in radians
  xy_goal_tolerance: 0.2 # In meters. Will literally stop within a 0.5m dia circle centered at the goal point
  latch_xy_goal_tolerance: true

#Forward simulation Params
  sim_time: 10
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 4
  vtheta_samples: 8


#Trajectory Scoring Params

  meter_scoring: true
  pdist_scale: 1
  gdist_scale: 5
  occdist_scale: 0.05
  heading_lookahead: 5 #Last Val: 10
  heading_scoring: false
  heading_scoring_timestep: 1 #Last Val: 4
  dwa: false
  publish_cost_grid_pc: true
  global_frame_id: odom

#Oscillation Prevention Params
  oscillation_reset_dist: 0.05

#Global Plan Params
  prune_plan: true

#Other params
  simple_attractor: false

